name: build

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build Docker image and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/terorie/redis-k8s-election:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
